version: '3'
services:
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
    - "9092:9092"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=kafka
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    restart: always
  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.6.0
    command: --kafka.server=kafka:9092 --web.listen-address=:8080
    restart: always
    ports:
    - 8080:8080

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
    - ./:/etc/prometheus/
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/tmp/prometheus'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
    - 9090:9090
    restart: always
  grafana:
    image: grafana/grafana:9.1.7-ubuntu
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
    - ./grafana/datasources:/etc/grafana/provisioning/datasources
    - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    - ./grafana/dashboards-content:/tmp/dashboards
    ports:
    - 3000:3000
    restart: always

  producer:
    build: .
    command: ruby /src/producer.rb
    volumes:
    - ./:/src
    restart: always
  worker:
   build: .
   command: ruby /src/worker.rb
   volumes:
   - ./:/src
   restart: always
