apiVersion: 1

datasources:
- name: prometheus
  type: prometheus
  access: server
  orgId: 1
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: false
  jsonData:
    timeInterval: 1s
